[bar.default]
capsule_group = []
center = [ "clock", "date" ]
end = [ "tray", "notifications", "clipboard", "network", "bluetooth", "volume", "brightness", "battery", "control-center" ]
font_family = "JetBrainsMono NF Medium"
font_weight = 400
margin_edge = 5
margin_ends = 10
padding = 10
start = [ "media", "audio_visualizer", "workspaces", "spacer_2", "active_window" ]

[theme]
builtin = "Tokyo-Night"

[widget.active_window]
capsule = true
font_scale = 1.1000000000000001
icon_size = 20
max_length = 800

[widget.audio_visualizer]
scale = 1.4000000000000001
width = 60

[widget.control-center]
glyph = "brand-zhihu"
scale = 1.25

[widget.media]
hide_artist = true
hide_when_no_media = true
max_length = 800
min_length = 0
scale = 1.1000000000000001

[widget.network]
scale = 1.1000000000000001
show_label = false

[widget.spacer_2]
type = "spacer"

[widget.volume]
glyph = "volume"
scale = 1.1000000000000001
